[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["ensure-no-std"]

[workspace.lints.rust]
unsafe_code = { level = "forbid", priority = 2 }
rust_2018_idioms = "deny"
nonstandard_style = "deny"
future_incompatible = "deny"
missing_docs = { level = "warn", priority = -1 }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
