[package]
name = "ensure-no-std"
publish = false
edition = "2018"

[dependencies]
impl-more = { path = "../crates/impl-more" }

[lints.rust]
rust-2018-idioms = "deny"
nonstandard-style = "deny"
future-incompatible = "deny"
